# Generated by Django 3.0.3 on 2020-03-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='x_coord',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='y_coord',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(default='You can travel freely through this space', max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='An open space', max_length=50),
        ),
    ]
