# Generated by Django 3.0.3 on 2020-03-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200304_2125'),
        ('adventure', '0002_auto_20200304_1631'),
    ]

    operations = [
    ]
