# Generated by Django 3.0.3 on 2020-03-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_player_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='moves',
            field=models.IntegerField(default=0),
        ),
    ]
