# Generated by Django 3.0.3 on 2020-03-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_player_moves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_id',
        ),
    ]
